
import sqlite3
import os
from pathlib import Path
import time
import uuid

# Configuration
DB_PATH = Path("db/mnemosyne.db")
SCHEMA_PATH = Path("db/schema.sql")

def setup_db():
    print(f"Setting up test database at {DB_PATH}...")
    
    # Ensure directory exists
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Connect (creates file)
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Apply schema
    print("Applying schema...")
    with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
        schema_sql = f.read()
        cursor.executescript(schema_sql)
        
    # Insert test data
    print("Inserting test data...")
    test_event = (
        str(uuid.uuid4()),      # session_uuid
        # timestamp_utc (datetime('now') handled by DB usually, but manual here for safety)
        int(time.time() * 1000), # unix_time
        "test_process.exe",     # process_name
        "Test Window Title",    # window_title
        12345,                  # window_hwnd
        0,                      # input_idle_ms
        0.5                     # input_intensity
    )
    
    # Note: timestamp_utc is generated by DEFAULT datetime('now') in schema usually
    cursor.execute("""
        INSERT INTO raw_events (
            session_uuid, 
            timestamp_utc, 
            unix_time, 
            process_name, 
            window_title, 
            window_hwnd, 
            input_idle_ms, 
            input_intensity
        ) VALUES (?, datetime('now'), ?, ?, ?, ?, ?, ?)
    """, test_event)
    
    conn.commit()
    conn.close()
    print("Database setup complete.")

if __name__ == "__main__":
    setup_db()
